name: Terraform CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  id-token: write
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::520369549554:role/GitHubActionsTerraformRolePractice
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.15.7"

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Init (bootstrap)
        run: terraform init
        working-directory: ./bootstrap

      - name: Terraform Validate (bootstrap)
        run: terraform validate
        working-directory: ./bootstrap
